### ISSUE TITLE
Theme doesn't show in my Fonts & Colors by installation using git

### ISSUE THREAD

**Issue by hanglearning** [dracula/xcode#6]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

![image](https://user-images.githubusercontent.com/13460425/33713036-8a824924-db84-11e7-9a71-3c4bc62658b9.png)

I followed the installation steps by git, but the theme doesn't show in my Fonts & Colors. I have restarted my Xcode and Mac and no avail. What could be the problem? Thanks!

**Comment by zenorocha** [comment]
Might be related to #5, right @victorg1991?

**Comment by victorg1991** [comment]
Yeah, from Xcode 8 the theme has to have the extension .xccolortheme to work

**Comment by zenorocha** [comment]
Awesome, closing this one since it didn't really change what it described. Renaming the file extension worked. Thanks @hanglearning!

**Comment by vishaldandge** [comment]
got same issue on Xcode 9.3

**Comment by juanarmond** [comment]
Still not working. How we can fix it?

**Comment by zenorocha** [comment]
Fixed: https://draculatheme.com/xcode/
