### ISSUE TITLE
Theme not shown in Fonts & Colors

### ISSUE THREAD

**Issue by vishaldandge** [dracula/xcode#7]
I can see theme file at `~/Library/Developer/Xcode/UserData/FontAndColorThemes/`. But its not visible in Xcode Preference.  In this path only dracula theme is present. Can't see anyother themes which are present in xcode preference settings.

**Comment by juanarmond** [comment]
Still not working. How we can fix it?

**Comment by philihp** [comment]
Was fixed by copying the file instead of symlinking it.

**Comment by philihp** [comment]
Was able to fix by copying the file instead of symlinking it

**Comment by riley-usagi** [comment]
Still not work.
Both variants.

**Comment by carc2019** [comment]
I've gotten it to work by moving the theme file to  ~/Library/Developer/Xcode/UserData/FontAndColorThemes/ and renaming the extension to .dvtcolortheme

**Comment by riley-usagi** [comment]
@carc2019 , thank you, man!

**Comment by gabriellet** [comment]
Moving this file directly into the folder (not using a symlink) worked for me too.
